# Generated by Django 4.2.30 on 2026-05-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Voiture'), ('motorcycle', 'Moto'), ('van', 'Utilitaire'), ('truck', 'Camion')], default='car', max_length=20)),
                ('fuel', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], default='gasoline', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], default='manual', max_length=20)),
                ('seats', models.IntegerField(default=5)),
                ('offer_type', models.CharField(choices=[('sale', 'Vente'), ('rent', 'Location'), ('both', 'Vente et Location')], default='sale', max_length=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
