# Generated by Django 4.2.30 on 2026-05-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('documents_received', 'Documents recus'), ('under_review', 'En verification'), ('approved', 'Approuve'), ('rejected', 'Refuse'), ('completed', 'Termine'), ('cancelled', 'Annule')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cni', 'Carte Nationale d Identite'), ('justificatif_domicile', 'Justificatif de domicile'), ('fiche_de_paie', 'Fiche de paie')], max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
            ],
        ),
    ]
