# Generated by Django 4.2.30 on 2026-05-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_status_clientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('option_type', models.CharField(choices=[('included', 'Inclus'), ('supplement', 'Supplement')], default='supplement', max_length=20)),
                ('billing_type', models.CharField(blank=True, choices=[('monthly', 'Mensuel'), ('one_time', 'Forfait unique')], max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['option_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='contracts.rentaloption'),
        ),
    ]
